02路由相关A/03路由namespace/apps/backend/urls.py
#!/usr/bin/env python
# -*- coding: UTF-8 -*-
'''
@Project ：Djangolearn 
@File    ：urls.py
@IDE     ：PyCharm 
@Author  ：百年
@Date    ：2025/10/15 12:27 
'''
from django.urls import path
from . import views
app_name = 'backend'
urlpatterns = [
    path('login/',views.login,name='login'),
    path('home/',views.home,name='home')
]

02路由相关A/03路由namespace/apps/web/urls.py
#!/usr/bin/env python
# -*- coding: UTF-8 -*-
'''
@Project ：Djangolearn 
@File    ：urls.py
@IDE     ：PyCharm 
@Author  ：百年
@Date    ：2025/10/15 12:29 
'''

from django.urls import path
from . import views

app_name = 'web'
urlpatterns = [
    path('home/',views.home,name='home' ),
    path('login/',views.login,name='login')
]

02路由相关A/03路由namespace/day3/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('web/',include('apps.web.urls',namespace='web')),
    path('backend/',include('apps.backend.urls',namespace='backend'))
]

02路由相关A/03路由namespace/apps/backend/models.py
from django.db import models

# Create your models here.

02路由相关A/03路由namespace/apps/web/models.py
from django.db import models

# Create your models here.

02路由相关A/03路由namespace/apps/backend/views.py
from django.shortcuts import render,HttpResponse,redirect
from django.urls import reverse
# Create your views here.
def home(request):
    return HttpResponse("这是主页")

def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        print(username,password)
        return redirect(reverse('backend:home'))
    return render(request,'backend/login.html')

02路由相关A/03路由namespace/apps/web/views.py
from django.shortcuts import render,HttpResponse,redirect
from django.urls import reverse


# Create your views here.

def home(request):
    return HttpResponse("这是主页")

def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        print(username,password)
        return redirect(reverse('web:home'))
    return render(request,'web/login.html')

02路由相关A/03路由namespace/templates/backend/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>管理人员登陆</title>
</head>
<body>
<form id="loginForm" action="{% url 'backend:login' %}" method="post">
    {% csrf_token %}
    <p><input placeholder="输入用户名" name="username" type="text"></p>
    <p><input placeholder="输入密码" name="password" type="text"></p>
    <button type="button" onclick="document.getElementById('loginForm').submit()">登录</button>
</form>
</body>
</html>

02路由相关A/03路由namespace/templates/web/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登陆</title>
</head>
<body>
<form id="loginForm" action="{% url 'web:login' %}" method="post">
    {% csrf_token %}
    <p><input placeholder="输入用户名" name="username" type="text"></p>
    <p><input placeholder="输入密码" name="password" type="text"></p>
    <button type="button" onclick="document.getElementById('loginForm').submit()">登录</button>
</form>
</body>
</html>